### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by rickmed** [foxhound87/rfx-stack#22] opened 2016-07-19 00:46 UTC
Hello, I got the following client warnings

WARNING in ./src/shared/stores/ui.js

C:\Users\rickm\Documents\Google Drive\Projects\NodeJS\rfx-stack\src\shared\stores\ui.js
  87:14  warning  Unexpected console statement  no-console

✖ 1 problem (0 errors, 1 warning)

---

WARNING in ./~/ajv/lib/async.js
Module not found: Error: Cannot resolve module 'regenerator' in C:\Users\rickm\Documents\Google Drive\Projects\NodeJS\rfx-stack\node_modules\ajv\lib
 @ ./~/ajv/lib/async.js 95:20-47

WARNING in ./~/ajv/lib/async.js
Module not found: Error: Cannot resolve module 'nodent' in C:\Users\rickm\Documents\Google Drive\Projects\NodeJS\rfx-stack\node_modules\ajv\lib
 @ ./~/ajv/lib/async.js 116:26-48

WARNING in ./~/ajv/lib/compile/index.js
Module not found: Error: Cannot resolve module 'js-beautify' in C:\Users\rickm\Documents\Google Drive\Projects\NodeJS\rfx-stack\node_modules\ajv\lib\compile
 @ ./~/ajv/lib/compile/index.js 8:42-69

---

Warning: Unknown prop `onTouchTap` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Overlay)
    in Overlay (created by Drawer)
    in div (created by Drawer)
    in Drawer (created by AppNav)
    in AppNav (created by AppLayout)
    in div
    in MatchMediaProvider (created by AppLayout)
    in AppLayout (created by RouterContext)
    in RouterContext
    in ContextProvider
    in MuiThemeProvider

**Comment by foxhound87** [comment] 2016-07-19 10:14
Hi, to remove the `ajv` warning you can add to your webpack config this plugin:
`new webpack.IgnorePlugin(/regenerator|nodent|js\-beautify/, /ajv/)`.
More info here: https://github.com/epoberezkin/ajv/issues/117

The `Unknown prop onTouchTap` warning is caused by a recent react update, it will be fixed by the official material-ui repo.  More info here: https://github.com/callemall/material-ui/issues/4670

The warning in the UI Store is caused by the use of `console.warn`, you can remove it if it's annoying.

**Closed as completed by foxhound87** 2016-07-19 10:14 UTC
Labels: question

**Comment by foxhound87** [comment] 2016-08-05 20:03
AJV Warnings Removed https://github.com/foxhound87/rfx-stack/commit/246f71ef5a4c876a22ca9cc95c43c43bcf210035 / https://github.com/foxhound87/rfx-stack/blob/246f71ef5a4c876a22ca9cc95c43c43bcf210035/webpack/config.client.js#L12
