### ISSUE TITLE
Warnings while running `web:dev`

### ISSUE THREAD

**Issue by osenvosem** [foxhound87/rfx-stack#25] opened 2016-08-04 10:11 UTC
osx 10.11
node 6.3.1

```
WARNING in ./src/shared/stores/ui.js

/Volumes/Data/development/dev/one/src/shared/stores/ui.js
  87:14  warning  Unexpected console statement  no-console

✖ 1 problem (0 errors, 1 warning)


WARNING in ./~/ajv/lib/async.js
Module not found: Error: Cannot resolve module 'regenerator' in /Volumes/Data/development/dev/one/node_modules/ajv/lib
 @ ./~/ajv/lib/async.js 95:20-47

WARNING in ./~/ajv/lib/async.js
Module not found: Error: Cannot resolve module 'nodent' in /Volumes/Data/development/dev/one/node_modules/ajv/lib
 @ ./~/ajv/lib/async.js 116:26-48

WARNING in ./~/ajv/lib/compile/index.js
Module not found: Error: Cannot resolve module 'js-beautify' in /Volumes/Data/development/dev/one/node_modules/ajv/lib/compile
 @ ./~/ajv/lib/compile/index.js 8:42-69
webpack: bundle is now VALID.
[BS] Proxying: http://localhost:3000
[BS] Access URLs:
 ----------------------------------
       Local: http://localhost:3100
    External: http://10.0.0.3:3100
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.0.3:3001
 ----------------------------------
route: /
Warning: Unknown prop `onTouchTap` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Overlay)
    in Overlay (created by Drawer)
    in div (created by Drawer)
    in Drawer (created by AppNav)
    in AppNav (created by AppLayout)
    in div (created by MatchMediaProvider)
    in MatchMediaProvider (created by AppLayout)
    in AppLayout (created by RouterContext)
    in RouterContext
    in ContextProvider
    in MuiThemeProvider
route: /favicon.ico
```

**Comment by foxhound87** [comment] 2016-08-04 17:34
Duplicate of: https://github.com/foxhound87/rfx-stack/issues/22

They are not errors but warnings. 

The `onTouchTap` warning is shown because we don't call `injectTapEventPlugin()` in development mode.

The warnings related to `ajv` can be removed using the webpack `IgnorePlugin`.
I think I have to add it to the webpack config because it seems many people are annoyed about these warnings.

**Closed as completed by foxhound87** 2016-08-04 17:34 UTC
Labels: duplicate

**Comment by foxhound87** [comment] 2016-08-05 20:03
AJV Warnings Removed https://github.com/foxhound87/rfx-stack/commit/246f71ef5a4c876a22ca9cc95c43c43bcf210035 / https://github.com/foxhound87/rfx-stack/blob/246f71ef5a4c876a22ca9cc95c43c43bcf210035/webpack/config.client.js#L12
